apiVersion: apps/v1
kind: Deployment
metadata:
  name: ioms-poc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ioms-poc
  template:
    metadata:
      labels:
        app: ioms-poc
    spec:
      containers:
      - name: wms-courierstub-app
        image: myacrpocrepo010823.azurecr.io/hariputhalapattu/wmscourierstub:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8087 
      - name: ioms-milestoneupdate-app
        image: myacrpocrepo010823.azurecr.io/hariputhalapattu/iomsmilestoneupdatepoc:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8086
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ioms-poc
    k8s-app: ioms-poc
  name: ioms-poc
spec:
  type: LoadBalancer
  ports:
  - name: wmscourierstub
    port: 87
    protocol: TCP
    targetPort: 8087
  - name: milestoneupdate
    port: 81
    protocol: TCP
    targetPort: 8086
  selector:
    app: ioms-poc
